# Generated by Django 3.0.4 on 2020-05-16 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged at')),
                ('logout_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Logout at')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='Counter label')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Counter value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'label')},
            },
        ),
    ]
